/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleProduto;
import java.awt.event.ActionEvent;
import static java.lang.System.console;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModeloFornecedor;
import model.ModeloProduto;

/**
 *
 * @author sfcvi
 */
public class FrmBalanco extends javax.swing.JFrame {

    private static FrmBalanco FrmFornecedorUnico;
    private String dataAtual;
    private int flag;
    ModeloProduto modProduto = new ModeloProduto();
    ControleProduto controlProduto = new ControleProduto();
    /**
     * Creates new form FrmFornecedor
     */
    public FrmBalanco() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocation(500, 100);
        this.setSize(500, 300);
        //setClosable(true);
        //add(new JLabel("Internal Frame Test"));        
        setVisible(true);

        InativarCampos();
        InativarMenus();
    }
    
    public static FrmBalanco getFrmFornecedor(){
        if (FrmFornecedorUnico == null) {
            FrmFornecedorUnico = new FrmBalanco();
        }

        return FrmFornecedorUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeFornecedor = new javax.swing.JTextField();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuSalvar = new javax.swing.JMenu();
        jMenuCancelar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Novo Saldo");

        jTextFieldNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFornecedorActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnify.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel12.setText("Código");

        jMenuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-document-box-plus-outline.png"))); // NOI18N
        jMenuNovo.setText("NOVO");
        jMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuNovo);

        jMenuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/content-save.png"))); // NOI18N
        jMenuSalvar.setText("SALVAR");
        jMenuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalvarMouseClicked(evt);
            }
        });
        jMenuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalvarActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalvar);

        jMenuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-cancel.png"))); // NOI18N
        jMenuCancelar.setText("CANCELAR");
        jMenuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNovoMouseClicked
        if (jMenuNovo.isEnabled()) {
            flag = 1;

            AtivarCampos();
            AtivarMenus();
            jMenuNovo.setEnabled(false);
        }
    }//GEN-LAST:event_jMenuNovoMouseClicked

    private void jMenuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMouseClicked
        String aux = jTextFieldCodigo.getText();
        //String aux = "50000";
        //System.out.println("a " + aux + " a");
        if (jMenuSalvar.isEnabled()) {
                modProduto.setSaldoProduto(Double.parseDouble(jTextFieldNomeFornecedor.getText()));
                modProduto.setIdProduto(Integer.parseInt(aux));

                controlProduto.EditarBalancoProduto(modProduto);

                limparCampos();
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuCancelar.setEnabled(false);
                AtivarMenus();
        }
    }//GEN-LAST:event_jMenuSalvarMouseClicked

    private void jMenuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalvarActionPerformed
        if (jMenuSalvar.isEnabled()) {
                modProduto.setSaldoProduto(Double.parseDouble(jTextFieldNomeFornecedor.getText()));
                controlProduto.EditarBalancoProduto(modProduto);

                limparCampos();
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuCancelar.setEnabled(true);
                AtivarCampos();
        }
    }//GEN-LAST:event_jMenuSalvarActionPerformed

    private void jMenuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCancelarMouseClicked
        if (jMenuCancelar.isEnabled()) {
            limparCampos();
            desativarCampos();

            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuCancelar.setEnabled(false);

            jTextFieldCodigo.setEnabled(true);
            jButtonPesquisar.setEnabled(true);

            InativarCampos();
        }
    }//GEN-LAST:event_jMenuCancelarMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jTextFieldCodigo.getText().equals("")) {
            FrmConsultaProduto frmFornecedor = new FrmConsultaProduto(null, true);
            

            frmFornecedor.setVisible(true);

            String idFornecedor = frmFornecedor.getIdProduto();
            String saldoProduto = frmFornecedor.getSaldoRealProduto();
            

            jTextFieldCodigo.setText(idFornecedor);
            jTextFieldNomeFornecedor.setText(saldoProduto);

        } else {

        }

        if (!jTextFieldCodigo.getText().equals("")) {
            jMenuSalvar.setEnabled(false);
            jMenuCancelar.setEnabled(false);
        }
        jMenuNovo.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFornecedorActionPerformed

    
    public void buscarUltimaInsercao() {
        try {
            modProduto.setSaldoProduto(Double.parseDouble(jTextFieldNomeFornecedor.getText()));
            modProduto = controlProduto.UltimaInsercao(modProduto);

            jTextFieldCodigo.setText(String.valueOf(modProduto.getIdProduto()));

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite um código válido");
        }
    }

    public void InativarCampos() {
        jTextFieldNomeFornecedor.setEnabled(false);
        
    }

    public void InativarMenus() {
        jMenuSalvar.setEnabled(false);
        jMenuCancelar.setEnabled(false);
    }

    public void AtivarCampos() {
        jTextFieldNomeFornecedor.setEnabled(true);
        
    }

    public void AtivarMenus() {
        jMenuSalvar.setEnabled(true);
        jMenuCancelar.setEnabled(true);
    }

    public void dataAtual() {
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date hoje = new Date();
        dataAtual = df.format(hoje);
    }

    public void limparCampos() {
        jTextFieldCodigo.setText("");
        jTextFieldNomeFornecedor.setText("");
        

       
        
    }

    public void desativarCampos() {
        jTextFieldNomeFornecedor.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBalanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBalanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBalanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBalanco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBalanco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancelar;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JMenu jMenuSalvar;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomeFornecedor;
    // End of variables declaration//GEN-END:variables

 
    /*private void setClosable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
}
