/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleFornecedor;
import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModeloFornecedor;

/**
 *
 * @author sfcvi
 */
public class FrmFornecedor extends javax.swing.JFrame {

    private static FrmFornecedor FrmFornecedorUnico;
    private String dataAtual;
    private int flag;
    ModeloFornecedor modFornecedor = new ModeloFornecedor();
    ControleFornecedor controlFornecedor = new ControleFornecedor();
    /**
     * Creates new form FrmFornecedor
     */
    public FrmFornecedor() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocation(500, 100);
        this.setSize(500, 300);
        //setClosable(true);
        //add(new JLabel("Internal Frame Test"));        
        setVisible(true);

        InativarCampos();
        InativarMenus();
    }
    
    public static FrmFornecedor getFrmFornecedor(){
        if (FrmFornecedorUnico == null) {
            FrmFornecedorUnico = new FrmFornecedor();
        }

        return FrmFornecedorUnico;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldNomeFornecedor = new javax.swing.JTextField();
        jTextFieldCodigo = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuSalvar = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();
        jMenuExcluir = new javax.swing.JMenu();
        jMenuCancelar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome");

        jTextFieldNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFornecedorActionPerformed(evt);
            }
        });

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnify.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel12.setText("Código");

        jMenuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-document-box-plus-outline.png"))); // NOI18N
        jMenuNovo.setText("NOVO");
        jMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuNovo);

        jMenuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/content-save.png"))); // NOI18N
        jMenuSalvar.setText("SALVAR");
        jMenuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalvarMouseClicked(evt);
            }
        });
        jMenuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalvarActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalvar);

        jMenuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/square-edit-outline.png"))); // NOI18N
        jMenuEditar.setText("EDITAR");
        jMenuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEditar);

        jMenuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jMenuExcluir.setText("EXCLUIR");
        jMenuBar1.add(jMenuExcluir);

        jMenuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-cancel.png"))); // NOI18N
        jMenuCancelar.setText("CANCELAR");
        jMenuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNovoMouseClicked
        if (jMenuNovo.isEnabled()) {
            flag = 1;

            AtivarCampos();
            AtivarMenus();
            jMenuNovo.setEnabled(false);
            jTextFieldCodigo.setEnabled(false);
            jButtonPesquisar.setEnabled(false);  
        }
    }//GEN-LAST:event_jMenuNovoMouseClicked

    private void jMenuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMouseClicked
        //String aux = jTextFieldCodigo.getText();
        String aux = "50000";
        System.out.println("a " + aux + " a");
        if (jMenuSalvar.isEnabled()) {
            
            if (aux == null || aux == ""){
            
                
                modFornecedor.setNomeFornecedor(jTextFieldNomeFornecedor.getText().toString());
                
                controlFornecedor.SalvarFornecedor(modFornecedor);
                limparCampos();
                AtivarMenus();
            }else{
                modFornecedor.setIdFornecedor(jTextFieldCodigo.getText());
                modFornecedor.setNomeFornecedor(jTextFieldNomeFornecedor.getText());

                controlFornecedor.EditarFornecedor(modFornecedor);

                limparCampos();
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                AtivarMenus();
            }
            /*
            if (flag == 1) {

                
                modFornecedor.setNomeFornecedor(jTextFieldNomeFornecedor.getText());

                controlFornecedor.SalvarFornecedor(modFornecedor);

                limparCampos();
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                AtivarMenus();

            } else {
                //Inicio do código para atualizar o produto
                
                modFornecedor.setNomeFornecedor(jTextFieldNomeFornecedor.getText());
               

                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                InativarCampos();
                AtivarMenus();

            }
            */
        }
    }//GEN-LAST:event_jMenuSalvarMouseClicked

    private void jMenuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalvarActionPerformed
        if (jMenuSalvar.isEnabled()) {
            if (flag == 1) {
                modFornecedor.setNomeFornecedor(jTextFieldNomeFornecedor.getText());
                controlFornecedor.SalvarFornecedor(modFornecedor);

                limparCampos();
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(true);
                AtivarCampos();
                

            } else {
                //Inicio do código para atualizar o produto
                modFornecedor.setNomeFornecedor(jTextFieldNomeFornecedor.getText());
                controlFornecedor.EditarFornecedor(modFornecedor);

                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(true);
                

            }
        }
    }//GEN-LAST:event_jMenuSalvarActionPerformed

    private void jMenuEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditarMouseClicked
        if (jMenuEditar.isEnabled()) {
            

            flag = 2;
            jMenuNovo.setEnabled(false);
            jMenuSalvar.setEnabled(true);
            jMenuEditar.setEnabled(false);
            jMenuExcluir.setEnabled(false);
            jMenuCancelar.setEnabled(true);

            AtivarCampos();

        }
    }//GEN-LAST:event_jMenuEditarMouseClicked

    private void jMenuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCancelarMouseClicked
        if (jMenuCancelar.isEnabled()) {
            limparCampos();
            desativarCampos();

            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(false);
            jMenuCancelar.setEnabled(false);

            jTextFieldCodigo.setEnabled(true);
            jButtonPesquisar.setEnabled(true);

            InativarCampos();
        }
    }//GEN-LAST:event_jMenuCancelarMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jTextFieldCodigo.getText().equals("")) {
            FrmConsultaFornecedor frmFornecedor = new FrmConsultaFornecedor(null, true);
            

            frmFornecedor.setVisible(true);

            String idFornecedor = frmFornecedor.getIdMarca();
            String nomeFornecedor = frmFornecedor.getNomeMarca();
            

            jTextFieldCodigo.setText(idFornecedor);
            jTextFieldNomeFornecedor.setText(nomeFornecedor);
            

        } else {

        }

        if (!jTextFieldCodigo.getText().equals("")) {
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(true);
            jMenuExcluir.setEnabled(true);
            jMenuCancelar.setEnabled(false);
        }
        jMenuNovo.setEnabled(true);
        jButtonPesquisar.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jTextFieldNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFornecedorActionPerformed

    
    public void buscarUltimaInsercao() {
        try {
            modFornecedor.setNomeFornecedor(jTextFieldNomeFornecedor.getText());
            modFornecedor = controlFornecedor.UltimaInsercao(modFornecedor);

            jTextFieldCodigo.setText(String.valueOf(modFornecedor.getIdFornecedor()));

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite um código válido");
        }
    }

    public void InativarCampos() {
        jTextFieldNomeFornecedor.setEnabled(false);
        
    }

    public void InativarMenus() {
        jMenuSalvar.setEnabled(false);
        jMenuEditar.setEnabled(false);
        jMenuExcluir.setEnabled(false);
        jMenuCancelar.setEnabled(false);
    }

    public void AtivarCampos() {
        jTextFieldNomeFornecedor.setEnabled(true);
        
    }

    public void AtivarMenus() {
        jMenuSalvar.setEnabled(true);
        jMenuEditar.setEnabled(false);
        jMenuExcluir.setEnabled(false);
        jMenuCancelar.setEnabled(true);
    }

    public void dataAtual() {
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date hoje = new Date();
        dataAtual = df.format(hoje);
    }

    public void limparCampos() {
        jTextFieldCodigo.setText("");
        jTextFieldNomeFornecedor.setText("");
        

       
        
    }

    public void desativarCampos() {
        jTextFieldNomeFornecedor.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancelar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuExcluir;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JMenu jMenuSalvar;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldNomeFornecedor;
    // End of variables declaration//GEN-END:variables

 
    /*private void setClosable(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
}
