/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperRunManager;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import util.CriarTabelas;
import view.ReportUtils;
import util.ConectaBanco;
import util.JDBCUtil;



/**
 *
 * @author Lucas Moraes Camacho
 */
public class FrmPrincipal extends javax.swing.JFrame {
    Connection con = null;
    Connection conection = null;
 
    public static final String relatorio_pdf
            = System.getProperty("user.dir") + "/src/report/relatorio.pdf";
    public static final String relatorio_fonte
            ="C:/Users/sfcvi/OneDrive/Documentos/NetBeansProjects/boardStop/src/report/produto.jasper";
     public static final String relatorio_compilado
            = System.getProperty("user.dir") + "\\src\\report\\produto.jasper";
     public static final String relatorio_marca_pdf
            = System.getProperty("user.dir") + "/src/report/relatorio_marca.pdf";
    public static final String relatorio_marca_fonte
            = System.getProperty("user.dir") + "/src/report/marca.jrxml";
     public static final String relatorio_marca_compilado
            = System.getProperty("user.dir") + "/src/report/marca.jasper";;
     public static final String relatorio_categoria_pdf
            = System.getProperty("user.dir") + "/src/report/categoria.pdf";
    public static final String relatorio_categoria_fonte
            = System.getProperty("user.dir") + "/src/report/categoria.jrxml";
     public static final String relatorio_categoria_compilado
            = System.getProperty("user.dir") + "/src/report/produto.jasper";;
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        JDBCUtil.init();
        con = JDBCUtil.getConnection();
        this.setExtendedState(MAXIMIZED_BOTH);
        
        ReportUtils.conexao();
    }

    FrmPrincipal(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuProdutoItem = new javax.swing.JMenu();
        jMenuItemProduto = new javax.swing.JMenuItem();
        jMenuItemCategoria = new javax.swing.JMenuItem();
        jMenuItemSubCategoria = new javax.swing.JMenuItem();
        jMenuItemMarca = new javax.swing.JMenuItem();
        jMenuItemProduto3 = new javax.swing.JMenuItem();
        jMenuCadastros1 = new javax.swing.JMenu();
        jMenuProdutoItem1 = new javax.swing.JMenu();
        jMenuItemProduto1 = new javax.swing.JMenuItem();
        jMenuItemCategoria1 = new javax.swing.JMenuItem();
        jMenuItemMarca1 = new javax.swing.JMenuItem();
        jMenuItemProduto2 = new javax.swing.JMenuItem();
        jMenuItemCategoria2 = new javax.swing.JMenuItem();
        jMenuItemMarca2 = new javax.swing.JMenuItem();
        jMenuCadastros3 = new javax.swing.JMenu();
        jMenuItemProduto5 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTOR DE JOGOS");
        setFocusable(false);

        javax.swing.GroupLayout jDesktopPanePrincipalLayout = new javax.swing.GroupLayout(jDesktopPanePrincipal);
        jDesktopPanePrincipal.setLayout(jDesktopPanePrincipalLayout);
        jDesktopPanePrincipalLayout.setHorizontalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDesktopPanePrincipalLayout.setVerticalGroup(
            jDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenuCadastros.setText("CADASTROS");

        jMenuProdutoItem.setText("Produto");

        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        jMenuProdutoItem.add(jMenuItemProduto);

        jMenuItemCategoria.setText("Categoria");
        jMenuItemCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoriaActionPerformed(evt);
            }
        });
        jMenuProdutoItem.add(jMenuItemCategoria);

        jMenuItemSubCategoria.setText("Sub-Categoria");
        jMenuItemSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSubCategoriaActionPerformed(evt);
            }
        });
        jMenuProdutoItem.add(jMenuItemSubCategoria);

        jMenuItemMarca.setText("Marca");
        jMenuItemMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarcaActionPerformed(evt);
            }
        });
        jMenuProdutoItem.add(jMenuItemMarca);

        jMenuItemProduto3.setText("Fornecedor");
        jMenuItemProduto3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemProduto3MouseClicked(evt);
            }
        });
        jMenuItemProduto3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProduto3ActionPerformed(evt);
            }
        });
        jMenuProdutoItem.add(jMenuItemProduto3);

        jMenuCadastros.add(jMenuProdutoItem);

        jMenuBarPrincipal.add(jMenuCadastros);

        jMenuCadastros1.setText("RELATÓRIOS");

        jMenuProdutoItem1.setText("Produto");

        jMenuItemProduto1.setText("Produto");
        jMenuItemProduto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProduto1ActionPerformed(evt);
            }
        });
        jMenuProdutoItem1.add(jMenuItemProduto1);

        jMenuItemCategoria1.setText("Categoria");
        jMenuItemCategoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoria1ActionPerformed(evt);
            }
        });
        jMenuProdutoItem1.add(jMenuItemCategoria1);

        jMenuItemMarca1.setText("Marca");
        jMenuItemMarca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarca1ActionPerformed(evt);
            }
        });
        jMenuProdutoItem1.add(jMenuItemMarca1);

        jMenuItemProduto2.setText("Produto");
        jMenuItemProduto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProduto2ActionPerformed(evt);
            }
        });
        jMenuProdutoItem1.add(jMenuItemProduto2);

        jMenuItemCategoria2.setText("Categoria");
        jMenuItemCategoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCategoria2ActionPerformed(evt);
            }
        });
        jMenuProdutoItem1.add(jMenuItemCategoria2);

        jMenuItemMarca2.setText("Marca");
        jMenuItemMarca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMarca2ActionPerformed(evt);
            }
        });
        jMenuProdutoItem1.add(jMenuItemMarca2);

        jMenuCadastros1.add(jMenuProdutoItem1);

        jMenuBarPrincipal.add(jMenuCadastros1);

        jMenuCadastros3.setText("MOVIMENTAÇÃO");

        jMenuItemProduto5.setText("Balanço");
        jMenuItemProduto5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProduto5ActionPerformed(evt);
            }
        });
        jMenuCadastros3.add(jMenuItemProduto5);

        jMenuBarPrincipal.add(jMenuCadastros3);

        setJMenuBar(jMenuBarPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
        FrmProduto form = null;
        form = new FrmProduto();
        form.setVisible(true);
        jDesktopPanePrincipal.add(form);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    private void jMenuItemCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoriaActionPerformed
        FrmCategoria form = null;
        form = new FrmCategoria();
        form.setVisible(true);
        jDesktopPanePrincipal.add(form);
    }//GEN-LAST:event_jMenuItemCategoriaActionPerformed

    private void jMenuItemSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSubCategoriaActionPerformed
        FrmSubCategoria form = null;
        form = new FrmSubCategoria();
        form.setVisible(true);
        jDesktopPanePrincipal.add(form);
    }//GEN-LAST:event_jMenuItemSubCategoriaActionPerformed

    private void jMenuItemMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarcaActionPerformed
        FrmMarca form = null;
        form = new FrmMarca();
        form.setVisible(true);
        jDesktopPanePrincipal.add(form);
    }//GEN-LAST:event_jMenuItemMarcaActionPerformed

    private void jMenuItemProduto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProduto1ActionPerformed
        System.out.println("Etapa0");
        JasperPrint impressao;
        System.out.println("Etapa1");
        System.out.println(con);
        try {
            //preenchimento do relatorio com a conexao e parametros
            System.out.println("Etapa2");
            impressao = JasperFillManager.fillReport(
                    //relatorio_compilado,
                    relatorio_fonte,
                    null,
                    con);
            System.out.println("Etapa3");
            //opcao de exportar o relatorio diretamente para arquivo
            JasperExportManager.exportReportToPdfFile(impressao, relatorio_pdf);
            System.out.println("Etapa4");
            JOptionPane.showMessageDialog(this, "Gerado o arquivo com sucesso: " + relatorio_pdf);
        } catch (JRException erro){
            erro.printStackTrace();
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
}
        
    }//GEN-LAST:event_jMenuItemProduto1ActionPerformed

    private void jMenuItemCategoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoria1ActionPerformed
        JasperPrint impressao;
        try {
            //preenchimento do relatorio com a conexao e parametros
            impressao = JasperFillManager.fillReport(
                    relatorio_categoria_compilado,
                    null,
                    con);

            //opcao de exportar o relatorio diretamente para arquivo
            JasperExportManager.exportReportToPdfFile(impressao, relatorio_pdf);

            JOptionPane.showMessageDialog(this, "Gerado o arquivo com sucesso: " + relatorio_pdf);
        } catch (JRException erro){
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
        
    }//GEN-LAST:event_jMenuItemCategoria1ActionPerformed

    private void jMenuItemMarca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarca1ActionPerformed
        JasperPrint impressao;
        try {
            //preenchimento do relatorio com a conexao e parametros
            impressao = JasperFillManager.fillReport(
                    relatorio_marca_compilado,
                    null,
                    con);

            //opcao de exportar o relatorio diretamente para arquivo
            JasperExportManager.exportReportToPdfFile(impressao, relatorio_pdf);

            JOptionPane.showMessageDialog(this, "Gerado o arquivo com sucesso: " + relatorio_pdf);
        } catch (JRException erro){
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
        
    }//GEN-LAST:event_jMenuItemMarca1ActionPerformed

    private void jMenuItemProduto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProduto2ActionPerformed
        JasperPrint impressao;
        try {

            // caso seja necessário, compila o relatório (caso deseja usar o jrxml)
            System.out.println("Etapa0");
            //JasperReport JR_compilado
                    //= JasperCompileManager.compileReport(relatorio_fonte);
            
            //preenchimento do relatorio com a conexao e parametros
            System.out.println("Etapa1");
            impressao = JasperFillManager.fillReport(
                    relatorio_fonte,
                    null,
                    con);

            //opcao de visualizar o relatorio
            System.out.println("Etapa2");
            JasperViewer.viewReport(impressao);
            System.out.println("Etapa3");
        } catch (JRException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jMenuItemProduto2ActionPerformed

    private void jMenuItemCategoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCategoria2ActionPerformed
        JasperPrint impressao;
        try {

            // caso seja necessário, compila o relatório (caso deseja usar o jrxml)
            JasperReport JR_compilado
                    = JasperCompileManager.compileReport(relatorio_categoria_fonte);
            
            //preenchimento do relatorio com a conexao e parametros
            impressao = JasperFillManager.fillReport(
                    JR_compilado,
                    null,
                    con);

            //opcao de visualizar o relatorio
            JasperViewer.viewReport(impressao);

        } catch (JRException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jMenuItemCategoria2ActionPerformed

    private void jMenuItemMarca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMarca2ActionPerformed
        JasperPrint impressao;
        try {

            // caso seja necessário, compila o relatório (caso deseja usar o jrxml)
            JasperReport JR_compilado
                    = JasperCompileManager.compileReport(relatorio_marca_fonte);
            
            //preenchimento do relatorio com a conexao e parametros
            impressao = JasperFillManager.fillReport(
                    JR_compilado,
                    null,
                    con);

            //opcao de visualizar o relatorio
            JasperViewer.viewReport(impressao);

        } catch (JRException erro) {
            System.err.println("Não foi possível exportar o relatório.\n\n" + erro);
        }
    }//GEN-LAST:event_jMenuItemMarca2ActionPerformed

    private void jMenuItemProduto3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProduto3ActionPerformed
        // TODO add your handling code here:
        FrmFornecedor.getFrmFornecedor().setVisible(true);
        
    }//GEN-LAST:event_jMenuItemProduto3ActionPerformed

    private void jMenuItemProduto3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemProduto3MouseClicked
        
        FrmFornecedor.getFrmFornecedor().setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemProduto3MouseClicked

    private void jMenuItemProduto5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProduto5ActionPerformed
        FrmBalanco form = null;
        form = new FrmBalanco();
        form.setVisible(true);
        jDesktopPanePrincipal.add(form);
    }//GEN-LAST:event_jMenuItemProduto5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPanePrincipal;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenu jMenuCadastros1;
    private javax.swing.JMenu jMenuCadastros3;
    private javax.swing.JMenuItem jMenuItemCategoria;
    private javax.swing.JMenuItem jMenuItemCategoria1;
    private javax.swing.JMenuItem jMenuItemCategoria2;
    private javax.swing.JMenuItem jMenuItemMarca;
    private javax.swing.JMenuItem jMenuItemMarca1;
    private javax.swing.JMenuItem jMenuItemMarca2;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JMenuItem jMenuItemProduto1;
    private javax.swing.JMenuItem jMenuItemProduto2;
    private javax.swing.JMenuItem jMenuItemProduto3;
    private javax.swing.JMenuItem jMenuItemProduto5;
    private javax.swing.JMenuItem jMenuItemSubCategoria;
    private javax.swing.JMenu jMenuProdutoItem;
    private javax.swing.JMenu jMenuProdutoItem1;
    // End of variables declaration//GEN-END:variables
}
