/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleProduto;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import model.ModeloProduto;
import util.CriarTabelas;
import view.FrmConsultaFornecedor;

/**
 *
 * @author Lucas Moraes Camacho
 */
public class FrmProduto extends javax.swing.JInternalFrame {

    private String dataAtual;
    private int flag;
    ModeloProduto modProduto = new ModeloProduto();
    ControleProduto controlProduto = new ControleProduto();

    /**
     * Creates new form FrmProduto
     */
    public FrmProduto() {
        initComponents();

        this.setLocation(500, 100);
        this.setSize(700, 544);
        setClosable(true);
        //add(new JLabel("Internal Frame Test"));        
        setVisible(true);

        InativarCampos();
        InativarMenus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jCheckBoxAtivo = new javax.swing.JCheckBox();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDataAlteracao = new javax.swing.JTextField();
        jTextFieldUsuarioCadastro = new javax.swing.JTextField();
        jTextFieldUsuarioAlteracao = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCodBarras = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter formataIntervalo = new javax.swing.text.MaskFormatter("#############");
            jTextFieldCodBarras = new javax.swing.JFormattedTextField(formataIntervalo);
        }catch(Exception e){
        }
        jLabel3 = new javax.swing.JLabel();
        jTextFieldSaldoMinimo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldIdMarca = new javax.swing.JTextField();
        jButtonPesquisarMarca = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldIdCategoria = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonPesquisarCategoria = new javax.swing.JButton();
        jTextFieldIdSubCategoria = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButtonPesquisarSubCategoria = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCodFabricante = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldFabricanteFornecedor = new javax.swing.JTextField();
        jButtonIncluirFabricanteFornecedor = new javax.swing.JButton();
        jComboBoxUnidade = new javax.swing.JComboBox<>();
        jTextFieldMarca = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldSubCategoria = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldCustoPraticado = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldValorVenda = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldMargemVenda = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuSalvar = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();
        jMenuExcluir = new javax.swing.JMenu();
        jMenuCancelar = new javax.swing.JMenu();

        setIconifiable(true);
        setTitle("CADASTRO DE PRODUTO");

        jLabel1.setText("Descrição");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnify.png"))); // NOI18N
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabel12.setText("Código");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jCheckBoxAtivo.setText("Ativo");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produto", "Serviço", "Mat. Prima" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCheckBoxAtivo)
                .addGap(89, 89, 89)
                .addComponent(jComboBoxTipo, 0, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBoxAtivo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setText("Cadastro");

        jTextFieldDataCadastro.setEnabled(false);

        jLabel9.setText("Alteração");

        jTextFieldDataAlteracao.setEnabled(false);

        jTextFieldUsuarioCadastro.setEnabled(false);

        jTextFieldUsuarioAlteracao.setEnabled(false);

        jLabel10.setText("Usuário");

        jLabel11.setText("Usuário");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFieldDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldUsuarioAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsuarioCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDataAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldUsuarioAlteracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Unidade");

        jLabel3.setText("Cód. Barras");

        jTextFieldSaldoMinimo.setText("0");

        jLabel4.setText("Saldo Min.");

        jTextField5.setEnabled(false);

        jLabel5.setText("Saldo");

        jTextFieldIdMarca.setText("0");

        jButtonPesquisarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnify.png"))); // NOI18N
        jButtonPesquisarMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarMarcaActionPerformed(evt);
            }
        });

        jLabel6.setText("Marca");

        jTextFieldIdCategoria.setText("0");

        jLabel7.setText("Categoria");

        jButtonPesquisarCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnify.png"))); // NOI18N
        jButtonPesquisarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarCategoriaActionPerformed(evt);
            }
        });

        jTextFieldIdSubCategoria.setText("0");

        jLabel13.setText("Sub-Categoria");

        jButtonPesquisarSubCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/magnify.png"))); // NOI18N
        jButtonPesquisarSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarSubCategoriaActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Fornecedores"));

        jLabel14.setText("Cód. Fabricante");

        jLabel15.setText("Fabricante/Fornecedor");

        jButtonIncluirFabricanteFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/plus.png"))); // NOI18N
        jButtonIncluirFabricanteFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonIncluirFabricanteFornecedorMouseClicked(evt);
            }
        });
        jButtonIncluirFabricanteFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirFabricanteFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldCodFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jTextFieldFabricanteFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIncluirFabricanteFornecedor)
                        .addGap(73, 73, 73))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addContainerGap(176, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCodFabricante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFabricanteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonIncluirFabricanteFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 202, Short.MAX_VALUE))
        );

        jComboBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UN", "KG", "LT", "PCT" }));

        jTextFieldMarca.setEnabled(false);

        jTextFieldCategoria.setEnabled(false);

        jTextFieldSubCategoria.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldSaldoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel6))
                                        .addGap(120, 120, 120))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldIdSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldSubCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonPesquisarSubCategoria))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonPesquisarCategoria))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                                        .addComponent(jTextFieldIdMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextFieldMarca)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonPesquisarMarca)))
                                        .addGap(18, 18, 18)))
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDescricao)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonPesquisar))
                                            .addComponent(jLabel1)
                                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 106, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(5, 5, 5))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSaldoMinimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPesquisarMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldIdMarca)
                                .addComponent(jTextFieldMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPesquisarCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonPesquisarSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldIdSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextFieldSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 129, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Principal", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Custos"));

        jLabel16.setText("Custo Anterior R$");

        jTextField14.setText("0");
        jTextField14.setEnabled(false);

        jLabel17.setText("Ult. Custo Nota R$");

        jTextField15.setText("0");
        jTextField15.setEnabled(false);

        jLabel18.setText("Custo Praticado R$");

        jTextFieldCustoPraticado.setText("0");

        jLabel19.setText("Custo Médio R$");

        jTextField17.setText("0");
        jTextField17.setEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jTextFieldCustoPraticado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCustoPraticado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Venda"));

        jLabel20.setText("Venda R$");

        jTextFieldValorVenda.setText("0");

        jLabel21.setText("Margem %");

        jTextFieldMargemVenda.setText("0");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jTextFieldMargemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMargemVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Preços", jPanel2);

        jMenuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-document-box-plus-outline.png"))); // NOI18N
        jMenuNovo.setText("NOVO");
        jMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuNovo);

        jMenuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/content-save.png"))); // NOI18N
        jMenuSalvar.setText("SALVAR");
        jMenuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalvarMouseClicked(evt);
            }
        });
        jMenuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalvarActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuSalvar);

        jMenuEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/square-edit-outline.png"))); // NOI18N
        jMenuEditar.setText("EDITAR");
        jMenuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEditar);

        jMenuExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/delete.png"))); // NOI18N
        jMenuExcluir.setText("EXCLUIR");
        jMenuBar1.add(jMenuExcluir);

        jMenuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-cancel.png"))); // NOI18N
        jMenuCancelar.setText("CANCELAR");
        jMenuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNovoMouseClicked
        if (jMenuNovo.isEnabled()) {
            flag = 1;

            AtivarCampos();
            AtivarMenus();
            jMenuNovo.setEnabled(false);
            jTextFieldCodigo.setEnabled(false);
            jButtonPesquisar.setEnabled(false);

            dataAtual();
            jTextFieldDataCadastro.setText(dataAtual);
        }
    }//GEN-LAST:event_jMenuNovoMouseClicked

    private void jMenuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCancelarMouseClicked
        if (jMenuCancelar.isEnabled()) {
            limparCampos();
            desativarCampos();

            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(false);
            jMenuCancelar.setEnabled(false);

            jTextFieldCodigo.setEnabled(true);
            jButtonPesquisar.setEnabled(true);

            InativarCampos();
        }
    }//GEN-LAST:event_jMenuCancelarMouseClicked

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        if (jTextFieldCodigo.getText().equals("")) {
            FrmConsultaProduto frmProduto = new FrmConsultaProduto(null, true);
            FrmConsultaMarca frmMarca = new FrmConsultaMarca(null, true);
            FrmConsultaCategoria frmCategoria = new FrmConsultaCategoria(null, true);
            FrmConsultaSubCategoria frmSubCategoria = new FrmConsultaSubCategoria(null, true);
            FrmConsultaFornecedor frmFornecedor = new FrmConsultaFornecedor(null, true);
            
            frmProduto.setVisible(true);

            String idProd = frmProduto.getIdProduto();
            String nomeProd = frmProduto.getNomeProduto();
            String idMarca =frmProduto.getIdMarca();
            String idCategoria =frmProduto.getIdCategoria();
            String idSubCategoria =frmProduto.getIdSubCategoria();
            String idFabricante = frmFornecedor.getIdMarca();
            String nomeMarca =frmMarca.getNomeMarca();
            String nomeCategoria =frmCategoria.getNomeCategoria();
            String nomeSubCategoria=frmSubCategoria.getNomeSubCategoria();
            String nomeFabricante = frmFornecedor.getNomeMarca();
            String custoPraticado = frmProduto.getCustoProduto();
            String margemProduto = frmProduto.getMargemProduto();
            String vendaVendaProduto = frmProduto.getVendaVendaProduto();
            String saldoProduto = frmProduto.getSaldoProduto();
            
            

            jTextFieldCodigo.setText(idProd);
            jTextFieldDescricao.setText(nomeProd);
            jTextFieldIdMarca.setText(idMarca);
            jTextFieldIdCategoria.setText(idCategoria);
            jTextFieldIdSubCategoria.setText(idSubCategoria);
            jTextFieldMarca.setText(nomeMarca);
            jTextFieldCategoria.setText(nomeCategoria);
            jTextFieldSubCategoria.setText(nomeSubCategoria);
            jTextFieldCodFabricante.setText(idFabricante);
            jTextFieldFabricanteFornecedor.setText(nomeFabricante);
            jTextFieldCustoPraticado.setText(custoPraticado);
            jTextFieldMargemVenda.setText(margemProduto);
            jTextFieldValorVenda.setText(vendaVendaProduto);
            jTextField5.setText(saldoProduto);

        } else {

        }

        if (!jTextFieldCodigo.getText().equals("")) {
            jMenuSalvar.setEnabled(false);
            jMenuEditar.setEnabled(true);
            jMenuExcluir.setEnabled(true);
            jMenuCancelar.setEnabled(false);
        }
        jMenuNovo.setEnabled(true);
        jButtonPesquisar.setEnabled(true);

    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jMenuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMouseClicked
        if (jMenuSalvar.isEnabled()) {
            if (flag == 1) {
                modProduto.setDataCadastroProduto(jTextFieldDataCadastro.getText());
                modProduto.setUsuarioCadastroProduto(jTextFieldUsuarioCadastro.getText());
                modProduto.setTipoProduto((String) jComboBoxTipo.getSelectedItem());
                if (jCheckBoxAtivo.isSelected()) {
                    modProduto.setAtivoProduto(true);
                } else {
                    modProduto.setAtivoProduto(false);
                }
                modProduto.setDescricaoProduto(jTextFieldDescricao.getText());
                modProduto.setUnidadeProduto((String) jComboBoxUnidade.getSelectedItem());
                modProduto.setCodBarrasProduto(jTextFieldCodBarras.getText());
                modProduto.setSaldoMinimoProduto(Double.parseDouble(jTextFieldSaldoMinimo.getText()));
                modProduto.setMarcaProduto(Integer.parseInt(jTextFieldIdMarca.getText()));
                modProduto.setCategoriaProduto(Integer.parseInt(jTextFieldIdCategoria.getText()));
                modProduto.setSubCategoriaProduto(Integer.parseInt(jTextFieldIdSubCategoria.getText()));

                modProduto.setCustoPraticadoProduto(Double.parseDouble(jTextFieldCustoPraticado.getText()));
                modProduto.setMargemProduto(Double.parseDouble(jTextFieldMargemVenda.getText()));
                modProduto.setValorVendaProduto(Double.parseDouble(jTextFieldValorVenda.getText()));
                controlProduto.SalvarProduto(modProduto);

                buscarUltimaInsercao();
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                InativarCampos();

            } else {
                //Inicio do código para atualizar o produto
                modProduto.setDataAlteracaoProduto(jTextFieldDataCadastro.getText());
                modProduto.setUsuarioAlteracaoProduto(jTextFieldUsuarioCadastro.getText());
                modProduto.setTipoProduto((String) jComboBoxTipo.getSelectedItem());
                if (jCheckBoxAtivo.isSelected()) {
                    modProduto.setAtivoProduto(true);
                } else {
                    modProduto.setAtivoProduto(false);
                }
                modProduto.setDescricaoProduto(jTextFieldDescricao.getText());
                modProduto.setUnidadeProduto((String) jComboBoxUnidade.getSelectedItem());
                modProduto.setCodBarrasProduto(jTextFieldCodBarras.getText());
                modProduto.setSaldoMinimoProduto(Double.parseDouble(jTextFieldSaldoMinimo.getText()));
                modProduto.setMarcaProduto(Integer.parseInt(jTextFieldIdMarca.getText()));
                modProduto.setCategoriaProduto(Integer.parseInt(jTextFieldIdCategoria.getText()));
                modProduto.setSubCategoriaProduto(Integer.parseInt(jTextFieldIdSubCategoria.getText()));

                modProduto.setCustoPraticadoProduto(Double.parseDouble(jTextFieldCustoPraticado.getText()));
                modProduto.setMargemProduto(Double.parseDouble(jTextFieldMargemVenda.getText()));
                modProduto.setValorVendaProduto(Double.parseDouble(jTextFieldValorVenda.getText()));
                controlProduto.EditarProduto(modProduto);

                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                InativarCampos();

            }
        }
    }//GEN-LAST:event_jMenuSalvarMouseClicked

    private void jButtonPesquisarMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarMarcaActionPerformed
        if (jTextFieldCodigo.getText().equals("")) {
            FrmConsultaMarca frmConsulta = new FrmConsultaMarca(null, true);
            frmConsulta.setVisible(true);

            String idMarca = frmConsulta.getIdMarca();
            String nomeMarca = frmConsulta.getNomeMarca();

            jTextFieldIdMarca.setText(idMarca);
            jTextFieldMarca.setText(nomeMarca);

        } else {

        }
    }//GEN-LAST:event_jButtonPesquisarMarcaActionPerformed

    private void jButtonPesquisarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarCategoriaActionPerformed
        if (jTextFieldCodigo.getText().equals("")) {
            FrmConsultaCategoria frmConsulta = new FrmConsultaCategoria(null, true);
            frmConsulta.setVisible(true);

            String idCategoria = frmConsulta.getIdCategoria();
            String nomeCategoria = frmConsulta.getNomeCategoria();

            jTextFieldIdCategoria.setText(idCategoria);
            jTextFieldCategoria.setText(nomeCategoria);

        } else {

        }
    }//GEN-LAST:event_jButtonPesquisarCategoriaActionPerformed

    private void jButtonPesquisarSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarSubCategoriaActionPerformed
        if (jTextFieldCodigo.getText().equals("")) {
            FrmConsultaSubCategoria frmConsulta = new FrmConsultaSubCategoria(null, true);
            frmConsulta.setVisible(true);

            String idCategoria = frmConsulta.getIdSubCategoria();
            String nomeSubCategoria = frmConsulta.getNomeSubCategoria();

            jTextFieldIdSubCategoria.setText(idCategoria);
            jTextFieldSubCategoria.setText(nomeSubCategoria);

        } else {

        }
    }//GEN-LAST:event_jButtonPesquisarSubCategoriaActionPerformed

    private void jMenuEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditarMouseClicked
        if (jMenuEditar.isEnabled()) {
            jTextFieldDataAlteracao.setText(dataAtual);

            flag = 2;
            jMenuNovo.setEnabled(false);
            jMenuSalvar.setEnabled(true);
            jMenuEditar.setEnabled(false);
            jMenuExcluir.setEnabled(false);
            jMenuCancelar.setEnabled(true);

            AtivarCampos();

        }
    }//GEN-LAST:event_jMenuEditarMouseClicked

    private void jMenuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalvarActionPerformed
        if (jMenuSalvar.isEnabled()) {
            if (flag == 1) {
                modProduto.setDataCadastroProduto(jTextFieldDataCadastro.getText());
                modProduto.setUsuarioCadastroProduto(jTextFieldUsuarioCadastro.getText());
                modProduto.setTipoProduto((String) jComboBoxTipo.getSelectedItem());
                if (jCheckBoxAtivo.isSelected()) {
                    modProduto.setAtivoProduto(true);
                } else {
                    modProduto.setAtivoProduto(false);
                }
                modProduto.setDescricaoProduto(jTextFieldDescricao.getText());
                modProduto.setUnidadeProduto((String) jComboBoxUnidade.getSelectedItem());
                modProduto.setCodBarrasProduto(jTextFieldCodBarras.getText());
                modProduto.setSaldoMinimoProduto(Double.parseDouble(jTextFieldSaldoMinimo.getText()));
                modProduto.setMarcaProduto(Integer.parseInt(jTextFieldIdMarca.getText()));
                modProduto.setCategoriaProduto(Integer.parseInt(jTextFieldIdCategoria.getText()));
                modProduto.setSubCategoriaProduto(Integer.parseInt(jTextFieldIdSubCategoria.getText()));

                modProduto.setCustoPraticadoProduto(Double.parseDouble(jTextFieldCustoPraticado.getText()));
                modProduto.setMargemProduto(Double.parseDouble(jTextFieldMargemVenda.getText()));
                modProduto.setValorVendaProduto(Double.parseDouble(jTextFieldValorVenda.getText()));
                modProduto.setFabricante(jTextFieldCodFabricante.getText());
                controlProduto.SalvarProduto(modProduto);

                buscarUltimaInsercao();
                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                InativarCampos();

            } else {
                //Inicio do código para atualizar o produto
                modProduto.setDataAlteracaoProduto(jTextFieldDataCadastro.getText());
                modProduto.setUsuarioAlteracaoProduto(jTextFieldUsuarioCadastro.getText());
                modProduto.setTipoProduto((String) jComboBoxTipo.getSelectedItem());
                if (jCheckBoxAtivo.isSelected()) {
                    modProduto.setAtivoProduto(true);
                } else {
                    modProduto.setAtivoProduto(false);
                }
                modProduto.setDescricaoProduto(jTextFieldDescricao.getText());
                modProduto.setUnidadeProduto((String) jComboBoxUnidade.getSelectedItem());
                modProduto.setCodBarrasProduto(jTextFieldCodBarras.getText());
                modProduto.setSaldoMinimoProduto(Double.parseDouble(jTextFieldSaldoMinimo.getText()));
                modProduto.setMarcaProduto(Integer.parseInt(jTextFieldIdMarca.getText()));
                modProduto.setCategoriaProduto(Integer.parseInt(jTextFieldIdCategoria.getText()));
                modProduto.setSubCategoriaProduto(Integer.parseInt(jTextFieldIdSubCategoria.getText()));

                modProduto.setCustoPraticadoProduto(Double.parseDouble(jTextFieldCustoPraticado.getText()));
                modProduto.setMargemProduto(Double.parseDouble(jTextFieldMargemVenda.getText()));
                modProduto.setValorVendaProduto(Double.parseDouble(jTextFieldValorVenda.getText()));
                modProduto.setFabricante(jTextFieldCodFabricante.getText());
                controlProduto.EditarProduto(modProduto);

                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuEditar.setEnabled(true);
                jMenuExcluir.setEnabled(true);
                jMenuCancelar.setEnabled(false);
                InativarCampos();

            }
        }
    }//GEN-LAST:event_jMenuSalvarActionPerformed

    private void jButtonIncluirFabricanteFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirFabricanteFornecedorActionPerformed
        if (jTextFieldCodigo.getText().equals("")) {
            FrmConsultaFornecedor frmConsulta = new FrmConsultaFornecedor(null, true);
            frmConsulta.setVisible(true);

            String idFab = frmConsulta.getIdMarca();
            String nomeFab = frmConsulta.getNomeMarca();

            jTextFieldCodFabricante.setText(idFab);
            jTextFieldFabricanteFornecedor.setText(nomeFab);
            

        } else {

        }
        
    }//GEN-LAST:event_jButtonIncluirFabricanteFornecedorActionPerformed

    private void jButtonIncluirFabricanteFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIncluirFabricanteFornecedorMouseClicked

        FrmConsultaFornecedor.getFrmConsultaFornecedor().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonIncluirFabricanteFornecedorMouseClicked

    public void buscarUltimaInsercao() {
        try {
            modProduto.setDescricaoProduto(jTextFieldDescricao.getText());
            modProduto = controlProduto.UltimaInsercao(modProduto);

            jTextFieldCodigo.setText(String.valueOf(modProduto.getIdProduto()));

        } catch (NumberFormatException erro) {
            JOptionPane.showMessageDialog(null, "Digite um código válido");
        }
    }

    public void InativarCampos() {
        jTextFieldDescricao.setEnabled(false);
        jComboBoxUnidade.setEnabled(false);
        jTextFieldCodBarras.setEnabled(false);
        jTextFieldSaldoMinimo.setEnabled(false);
        jTextFieldIdMarca.setEnabled(false);
        jTextFieldIdCategoria.setEnabled(false);
        jTextFieldIdSubCategoria.setEnabled(false);
        jTextFieldCodFabricante.setEnabled(false);
        jTextFieldFabricanteFornecedor.setEnabled(false);

        jCheckBoxAtivo.setEnabled(false);

        jComboBoxTipo.setEnabled(false);

        jTextFieldCustoPraticado.setEnabled(false);
        jTextFieldMargemVenda.setEnabled(false);
        jTextFieldValorVenda.setEnabled(false);

        jButtonPesquisarMarca.setEnabled(false);
        jButtonPesquisarCategoria.setEnabled(false);
        jButtonPesquisarSubCategoria.setEnabled(false);
        jButtonIncluirFabricanteFornecedor.setEnabled(false);
    }

    public void InativarMenus() {
        jMenuSalvar.setEnabled(false);
        jMenuEditar.setEnabled(false);
        jMenuExcluir.setEnabled(false);
        jMenuCancelar.setEnabled(false);
    }

    public void AtivarCampos() {
        jTextFieldDescricao.setEnabled(true);
        jComboBoxUnidade.setEnabled(true);
        jTextFieldCodBarras.setEnabled(true);
        jTextFieldSaldoMinimo.setEnabled(true);
        jTextFieldIdMarca.setEnabled(true);
        jTextFieldIdCategoria.setEnabled(true);
        jTextFieldIdSubCategoria.setEnabled(true);
        jTextFieldCodFabricante.setEnabled(true);
        jTextFieldFabricanteFornecedor.setEnabled(true);

        jCheckBoxAtivo.setEnabled(true);

        jComboBoxTipo.setEnabled(true);

        jTextFieldCustoPraticado.setEnabled(true);
        jTextFieldMargemVenda.setEnabled(true);
        jTextFieldValorVenda.setEnabled(true);

        jButtonPesquisarMarca.setEnabled(true);
        jButtonPesquisarCategoria.setEnabled(true);
        jButtonPesquisarSubCategoria.setEnabled(true);
        jButtonIncluirFabricanteFornecedor.setEnabled(true);
    }

    public void AtivarMenus() {
        jMenuSalvar.setEnabled(true);
        jMenuEditar.setEnabled(false);
        jMenuExcluir.setEnabled(false);
        jMenuCancelar.setEnabled(true);
    }

    public void dataAtual() {
        SimpleDateFormat df = new SimpleDateFormat("dd-MM-yyyy");
        Date hoje = new Date();
        dataAtual = df.format(hoje);
    }

    public void limparCampos() {
        jTextFieldCodigo.setText("");
        jTextFieldUsuarioCadastro.setText("");
        jTextFieldUsuarioAlteracao.setText("");
        jTextFieldDescricao.setText("");
        jTextFieldCodBarras.setText("");
        jTextFieldSaldoMinimo.setText("");
        jTextFieldIdMarca.setText("");
        jTextFieldIdCategoria.setText("");
        jTextFieldIdSubCategoria.setText("");
        jTextFieldCodFabricante.setText("");
        jTextFieldFabricanteFornecedor.setText("");
        jTextFieldDataCadastro.setText("");
        jTextFieldDataAlteracao.setText("");
        jTextFieldMarca.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldSubCategoria.setText("");

        jCheckBoxAtivo.setSelected(false);

        //jComboBoxTipo.setEnabled(true);
        jTextFieldCustoPraticado.setText("");
        jTextFieldMargemVenda.setText("");
        jTextFieldValorVenda.setText("");
    }

    public void desativarCampos() {
        jTextFieldDescricao.setEnabled(false);
        jComboBoxUnidade.setEnabled(false);
        jTextFieldCodBarras.setEnabled(false);
        jTextFieldSaldoMinimo.setEnabled(false);
        jTextFieldIdMarca.setEnabled(false);
        jTextFieldIdCategoria.setEnabled(false);
        jTextFieldIdSubCategoria.setEnabled(false);
        jTextFieldCodFabricante.setEnabled(false);
        jTextFieldFabricanteFornecedor.setEnabled(false);

        jCheckBoxAtivo.setEnabled(false);

        jComboBoxTipo.setEnabled(false);

        jTextFieldCustoPraticado.setEnabled(false);
        jTextFieldMargemVenda.setEnabled(false);
        jTextFieldValorVenda.setEnabled(false);

        jButtonPesquisarMarca.setEnabled(false);
        jButtonPesquisarCategoria.setEnabled(false);
        jButtonPesquisarSubCategoria.setEnabled(false);
        jButtonIncluirFabricanteFornecedor.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIncluirFabricanteFornecedor;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonPesquisarCategoria;
    private javax.swing.JButton jButtonPesquisarMarca;
    private javax.swing.JButton jButtonPesquisarSubCategoria;
    private javax.swing.JCheckBox jCheckBoxAtivo;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JComboBox<String> jComboBoxUnidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancelar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuExcluir;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JMenu jMenuSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldCodBarras;
    private javax.swing.JTextField jTextFieldCodFabricante;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCustoPraticado;
    private javax.swing.JTextField jTextFieldDataAlteracao;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldFabricanteFornecedor;
    private javax.swing.JTextField jTextFieldIdCategoria;
    private javax.swing.JTextField jTextFieldIdMarca;
    private javax.swing.JTextField jTextFieldIdSubCategoria;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldMargemVenda;
    private javax.swing.JTextField jTextFieldSaldoMinimo;
    private javax.swing.JTextField jTextFieldSubCategoria;
    private javax.swing.JTextField jTextFieldUsuarioAlteracao;
    private javax.swing.JTextField jTextFieldUsuarioCadastro;
    private javax.swing.JTextField jTextFieldValorVenda;
    // End of variables declaration//GEN-END:variables
}
