/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControleUsuario;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.ModeloUsuario;
import util.AtualizaSistema;
import util.CriarTabelas;

/**
 *
 * @author Lucas Moraes Camacho
 */
public class FrmUsuario extends javax.swing.JFrame {
    private static FrmUsuario FrmUsuarioUnico;
    ModeloUsuario modUsuario = new ModeloUsuario();
    ControleUsuario controlUsuario = new ControleUsuario();
    
    private int flag;

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocation(500, 100);
        this.setSize(400, 200);
        
        InativarMenus();
        
        //Método não encerrar a tela sem fechar
        
    }

    public static FrmUsuario getFrmUsuario(){
        if (FrmUsuarioUnico == null) {
            FrmUsuarioUnico = new FrmUsuario();
        }

        return FrmUsuarioUnico;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSenha = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuSalvar = new javax.swing.JMenu();
        jMenuCancelar = new javax.swing.JMenu();

       
        setTitle("CADASTRO DE CATEGORIA");

        jLabel1.setText("Usuário");

        jLabel2.setText("Senha");

        jMenuNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-document-box-plus-outline.png"))); // NOI18N
        jMenuNovo.setText("NOVO");
        jMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNovoMouseClicked(evt);
            }
        });
        jMenuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuNovo);

        jMenuSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/content-save.png"))); // NOI18N
        jMenuSalvar.setText("SALVAR");
        jMenuSalvar.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jMenuSalvarItemStateChanged(evt);
            }
        });
        jMenuSalvar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuSalvarMenuSelected(evt);
            }
        });
        jMenuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuSalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuSalvarMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuSalvarMousePressed(evt);
            }
        });
        jMenuSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalvarActionPerformed(evt);
            }
        });
        jMenuSalvar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuSalvarKeyPressed(evt);
            }
        });
        jMenuBar1.add(jMenuSalvar);

        jMenuCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/file-cancel.png"))); // NOI18N
        jMenuCancelar.setText("CANCELAR");
        jMenuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCancelar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(263, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNovoMouseClicked
       if(jMenuNovo.isEnabled()){
            flag = 1;
           
            //Chama caso botão esteja habilitado
            jMenuSalvar.setEnabled(true);
            jMenuCancelar.setEnabled(true);
            jMenuNovo.setEnabled(false);
            jTextFieldUsuario.setEnabled(true); 
            jTextFieldSenha.setEnabled(true); 
            
            jTextFieldUsuario.setText("");
            jTextFieldSenha.setText("");
        }else{
            //Chama caso botão esteja não habilitado
        }
    }//GEN-LAST:event_jMenuNovoMouseClicked

    private void jMenuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCancelarMouseClicked
        if(jMenuCancelar.isEnabled()){            
            jMenuNovo.setEnabled(true);
            jMenuSalvar.setEnabled(false);
            jMenuCancelar.setEnabled(false);

            jTextFieldUsuario.setEnabled(false); 
            jTextFieldUsuario.setText("");
            jTextFieldSenha.setEnabled(false); 
            jTextFieldSenha.setText("");
        }
    }//GEN-LAST:event_jMenuCancelarMouseClicked

    private void jMenuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMouseClicked
        if(jMenuSalvar.isEnabled()){
                modUsuario.setUsuario(jTextFieldUsuario.getText());
                modUsuario.setSenha(jTextFieldSenha.getText());
                controlUsuario.SalvarUsuario(modUsuario);

                jMenuNovo.setEnabled(true);
                jMenuSalvar.setEnabled(false);
                jMenuCancelar.setEnabled(false);        
                jTextFieldUsuario.setEnabled(false);
                jTextFieldSenha.setEnabled(false);          
        }
    }//GEN-LAST:event_jMenuSalvarMouseClicked

    private void jMenuSalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalvarMouseEntered

    private void jMenuSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalvarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalvarActionPerformed

    private void jMenuSalvarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuSalvarMenuSelected
        
    }//GEN-LAST:event_jMenuSalvarMenuSelected

    private void jMenuSalvarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuSalvarKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalvarKeyPressed

    private void jMenuSalvarItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jMenuSalvarItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalvarItemStateChanged

    private void jMenuSalvarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuSalvarMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuSalvarMousePressed

    private void jMenuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoActionPerformed
        
    }//GEN-LAST:event_jMenuNovoActionPerformed

    public void InativarMenus(){
        jMenuSalvar.setEnabled(false);
        jMenuCancelar.setEnabled(false); 
        
        jTextFieldUsuario.setEnabled(false);
        jTextFieldSenha.setEnabled(false);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCancelar;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JMenu jMenuSalvar;
    private javax.swing.JTextField jTextFieldSenha;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables

    
}
